services:
  backend:
    build:
      context: fastapi_backend
    env_file:
      - ./fastapi_backend/.env
    environment:
      - TZ=Asia/Seoul
      - DATABASE_URL=postgresql+asyncpg://postgres:439e19e7328d37abb598d1603dbe9eca8abef29433544c1e@db:5432/app
      - REDIS_URL=redis://redis:6379/0
      - OPENAPI_OUTPUT_FILE=./shared-data/openapi.json
    ports:
      - "8000:8000"
    volumes:
      # - ./fastapi_backend:/app
      # - fastapi-venv:/app/.venv
      - ./local-shared-data:/app/shared-data
    depends_on:
      - db
      - redis
  redis:
    image: redis:8.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
  db:
    image: postgres:18.6-trixie
    environment:
      TZ: Asia/Seoul
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 439e19e7328d37abb598d1603dbe9eca8abef29433544c1e
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
  db_test:
    image: postgres:18.6-trixie
    environment:
      TZ: Asia/Seoul
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 439e19e7328d37abb598d1603dbe9eca8abef29433544c1e
      POSTGRES_DB: app
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/18/docker
  frontend:
    build:
      context: ./nextjs-frontend
    ports:
      - "3000:3000"
    environment:
      TZ: Asia/Seoul
      NODE_ENV: production
      API_BASE_URL: http://backend:8000
      OPENAPI_OUTPUT_FILE: ./shared-data/openapi.json
    volumes:
      - ./local-shared-data:/app/shared-data
  scheduler:
    build:
      context: fastapi_backend
    command: ["/app/.venv/bin/python", "-m", "scheduler.runner"]
    environment:
      - TZ=Asia/Seoul
      - DATABASE_URL=postgresql+asyncpg://postgres:439e19e7328d37abb598d1603dbe9eca8abef29433544c1e@db:5432/app
    depends_on:
      - db

volumes:
  postgres_data:
  postgres_test_data:
  redis_data: