"""split schedule from job_key

Revision ID: 86bd5d37ac9e
Revises: af599fe5d712
Create Date: 2026-09-04 18:19:12.016194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86bd5d37ac9e'
down_revision: Union[str, None] = 'af599fe5d712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cron_expression', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='Asia/Seoul', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('concurrency_key', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scheduler_schedules_enabled', 'scheduler_schedules', ['job_key', 'enabled'], unique=False)
    op.create_index(op.f('ix_scheduler_schedules_job_key'), 'scheduler_schedules', ['job_key'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.String(length=64)), server_default='{}', nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.drop_table('scheduler_jobs')
    op.add_column('scheduler_job_log', sa.Column('job_key', sa.String(length=100), nullable=False))
    op.add_column('scheduler_job_log', sa.Column('queue_id', sa.UUID(), nullable=True))
    op.add_column('scheduler_job_log', sa.Column('schedule_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_scheduler_job_log_job_id'), table_name='scheduler_job_log')
    op.drop_index(op.f('ix_scheduler_job_log_job_id_started_at'), table_name='scheduler_job_log')
    op.create_index(op.f('ix_scheduler_job_log_job_key'), 'scheduler_job_log', ['job_key'], unique=False)
    op.create_index('ix_scheduler_job_log_job_key_started_at', 'scheduler_job_log', ['job_key', 'started_at'], unique=False)
    op.create_index(op.f('ix_scheduler_job_log_queue_id'), 'scheduler_job_log', ['queue_id'], unique=False)
    op.create_index(op.f('ix_scheduler_job_log_schedule_id'), 'scheduler_job_log', ['schedule_id'], unique=False)
    op.create_foreign_key('fk_scheduler_job_log_queue_id', 'scheduler_job_log', 'scheduler_job_queue', ['queue_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'scheduler_job_log', 'scheduler_schedules', ['schedule_id'], ['id'])
    op.drop_column('scheduler_job_log', 'job_id')
    op.add_column('scheduler_job_queue', sa.Column('schedule_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_scheduler_job_queue_schedule_id'), 'scheduler_job_queue', ['schedule_id'], unique=False)
    op.create_foreign_key(None, 'scheduler_job_queue', 'scheduler_schedules', ['schedule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scheduler_job_queue', type_='foreignkey')
    op.drop_index(op.f('ix_scheduler_job_queue_schedule_id'), table_name='scheduler_job_queue')
    op.drop_column('scheduler_job_queue', 'schedule_id')
    op.add_column('scheduler_job_log', sa.Column('job_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'scheduler_job_log', type_='foreignkey')
    op.drop_constraint('fk_scheduler_job_log_queue_id', 'scheduler_job_log', type_='foreignkey')
    op.drop_index(op.f('ix_scheduler_job_log_schedule_id'), table_name='scheduler_job_log')
    op.drop_index(op.f('ix_scheduler_job_log_queue_id'), table_name='scheduler_job_log')
    op.drop_index('ix_scheduler_job_log_job_key_started_at', table_name='scheduler_job_log')
    op.drop_index(op.f('ix_scheduler_job_log_job_key'), table_name='scheduler_job_log')
    op.create_index(op.f('ix_scheduler_job_log_job_id_started_at'), 'scheduler_job_log', ['job_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_scheduler_job_log_job_id'), 'scheduler_job_log', ['job_id'], unique=False)
    op.drop_column('scheduler_job_log', 'schedule_id')
    op.drop_column('scheduler_job_log', 'queue_id')
    op.drop_column('scheduler_job_log', 'job_key')
    op.create_table('scheduler_jobs',
    sa.Column('job_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('cron_hour', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False),
    sa.Column('cron_minute', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('timezone', sa.VARCHAR(length=64), server_default=sa.text("'Asia/Seoul'::character varying"), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_delete', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('job_key', name=op.f('scheduler_jobs_pkey'))
    )
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_scheduler_schedules_job_key'), table_name='scheduler_schedules')
    op.drop_index('ix_scheduler_schedules_enabled', table_name='scheduler_schedules')
    op.drop_table('scheduler_schedules')
    # ### end Alembic commands ###
