"""scheduler ids uuid v7

Revision ID: af599fe5d712
Revises: f2d7e14dd4af
Create Date: 2026-09-02 17:41:12.229947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'af599fe5d712'
down_revision: Union[str, None] = 'f2d7e14dd4af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scheduler_job_log', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('scheduler_job_queue', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('scheduler_job_queue', 'related_log_id',
               existing_type=sa.BIGINT(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_foreign_key(None, 'scheduler_job_queue', 'scheduler_job_log', ['related_log_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scheduler_job_queue', type_='foreignkey')
    op.alter_column('scheduler_job_queue', 'related_log_id',
               existing_type=sa.UUID(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('scheduler_job_queue', 'id',
               existing_type=sa.UUID(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('scheduler_job_log', 'id',
               existing_type=sa.UUID(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
