"""update scheduler

Revision ID: f6e1569cffd6
Revises: 87ab01be428b
Create Date: 2026-09-01 10:18:20.773453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6e1569cffd6'
down_revision: Union[str, None] = '87ab01be428b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_job_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='RUNNING', nullable=False),
    sa.Column('elapsed_sec', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduler_job_log_job_id'), 'scheduler_job_log', ['job_id'], unique=False)
    op.create_index('ix_scheduler_job_log_job_id_started_at', 'scheduler_job_log', ['job_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_scheduler_job_log_started_at'), 'scheduler_job_log', ['started_at'], unique=False)
    op.create_table('scheduler_jobs',
    sa.Column('job_key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('cron_hour', sa.Integer(), server_default='3', nullable=False),
    sa.Column('cron_minute', sa.Integer(), server_default='0', nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='Asia/Seoul', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('job_key')
    )
    op.create_table('scheduler_job_queue',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_key', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('related_log_id', sa.BigInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduler_job_queue_job_key'), 'scheduler_job_queue', ['job_key'], unique=False)
    op.create_index(op.f('ix_scheduler_job_queue_requested_by_user_id'), 'scheduler_job_queue', ['requested_by_user_id'], unique=False)
    op.create_index('ix_scheduler_job_queue_status_created', 'scheduler_job_queue', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scheduler_job_queue_status_created', table_name='scheduler_job_queue')
    op.drop_index(op.f('ix_scheduler_job_queue_requested_by_user_id'), table_name='scheduler_job_queue')
    op.drop_index(op.f('ix_scheduler_job_queue_job_key'), table_name='scheduler_job_queue')
    op.drop_table('scheduler_job_queue')
    op.drop_table('scheduler_jobs')
    op.drop_index(op.f('ix_scheduler_job_log_started_at'), table_name='scheduler_job_log')
    op.drop_index('ix_scheduler_job_log_job_id_started_at', table_name='scheduler_job_log')
    op.drop_index(op.f('ix_scheduler_job_log_job_id'), table_name='scheduler_job_log')
    op.drop_table('scheduler_job_log')
    # ### end Alembic commands ###
